import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Looper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  className,
}: {
  children: React.ReactNode
  className?: string
}) {
  return (
    <>
      <div className={`${inter.className} ${className}`}>
        {children}
      </div>
    </>
  )
}
